# encoding: utf-8
---
recipe:
  Rx: others/recipes/config
  args:
    - schema=rime_ice
  description: >-
    启用双拼，并添加反查、英文派生的双拼支持。
      - rime_ice（雾凇拼音、全拼）
      - double_pinyin（自然码双拼）
      - double_pinyin_flypy（小鹤双拼）
      - double_pinyin_mspy（微软双拼）
      - double_pinyin_sogou（搜狗双拼）
      - double_pinyin_abc（智能 ABC 双拼）
      - double_pinyin_jiajia（拼音加加双拼）
      - double_pinyin_ziguang（紫光双拼）

patch_files:
  default.custom.yaml:
    - patch/+:
        schema_list:
          - schema: ${schema:-rime_ice}

  radical_pinyin.custom.yaml:
    - patch/+:
        speller/algebra:
          __include: radical_pinyin.schema.yaml:/algebra_${schema:-rime_ice}

  melt_eng.custom.yaml:
    - patch/+:
        speller/algebra:
          __include: melt_eng.schema.yaml:/algebra_${schema:-rime_ice}
