name: Lint and Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-linux:
    name: Lint and Test
    runs-on: ubuntu-26.04
    if: github.repository == 'iDvel/rime-ice'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install lint dependencies
        run: |
          sudo apt install -y lua5.5 luarocks yamllint
          sudo luarocks install luacheck

      - name: Cache rime cli bundle
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/rime-cli-cache/rime-cli.zip
          key: rime-cli

      - name: Run lint
        run: make -C others/script lint

      - name: Run test suite
        env:
          RIME_CLI_URL: https://github.com/iDvel/rime-ice/releases/download/tools/rime-1.17.0-lua-5.4-cli-linux-x86_64.zip
          RIME_CLI_CACHE_PATH: ${{ runner.temp }}/rime-cli-cache/rime-cli.zip
        run: make -C others/script smoke
